### ISSUE TITLE
Gettin error when going to review step

### ISSUE THREAD

**Issue by slinkstep** [FlatFilers/Adapter#42]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

   "flatfile-csv-importer": "^0.2.9"

* **Summary**

I have a simple two fields test with two rows of data and no validators. The importers matches the data but when in click review it fires an error. If i use the version 1 it won´t happen. I'm testing with .csv and xslx.

Error: 

Object
name: "TypeError"
message: "Cannot read property 'includes' of undefined"
stack: "TypeError: Cannot read property 'includes' of undefined↵    at FlatfileImporter.$recordHook (http://localhost:3000/static/js/main.chunk.js:3293:23)↵    at Object.dataHookCallback (http://localhost:3000/static/js/0.chunk.js:80856:44)↵    at http://localhost:3000/static/js/0.chunk.js:79762:48↵    at new Promise (<anonymous>)↵    at handleMessageEvent (http://localhost:3000/static/js/0.chunk.js:79761:11)"
__proto__: Object

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by slinkstep** [comment]
I solved it with the support team. It was my mistake.
